Add Esperanto Translations
reinhello/NReader pull request #122
Opened 2022-09-27 04:39 UTC by darccyy

Add folder `eo` to `localisation`, containing translations of all `json` files into Esperanto.
These translations are not perfect, but they should be good enough.

Notes:
Acronyms such as 'NSFW' were left the same.
I assumed these translations were accurate:
-   premium = premio
-   bot = roboto
-   Discord Server = Diskorda Servilo
-   NSFW = NSFW (otherwise NSPL for Ne Sekura Por Laborejo)
-   doujin (fandom) = fervolularo (aro de fervoluloj)
-   slash command = oblikva ordono
-   tag = etikedo
-   pong (return of ping command) = respondo (responce)
-   run (a command) = ordoni
-   memory (RAM) = memorilo
-   bookmark = legosignoj (plural)

`.vscode/settings.json` was also added for for tab size formatting.

`localisation/eo/ESPERANTO_NOTES.md` can be deleted, it is just a mirror of this PR for future reference.

2022-09-27 04:41 UTC, darccyy commented
Hope this is helpful :)

2022-09-27 07:57 UTC, reinhello commented
Thank you for your contribution! I don't speak or know the language but I think the translations are all good, will add them soon in [Crowdin](https://crowdin.com/project/nreader) for everyone else to contribute/proofread.

2022-09-27 07:59 UTC, reinhello requested changes

2022-09-27 07:59 UTC, reinhello commented on localisation/eo/ESPERANTO_NOTES.md
> +-   bookmark = legosignoj (plural)
You may delete this file and everything else should be good.

2022-09-27 08:10 UTC, reinhello commented
One important thing to notice is that you'll also need to edit a few of the framework's code in order to fully support this language. Feel free to join the [Discord server](https://discord.gg/b7AW2Zkcsw) for devs discussion if you like to.

2022-09-27 12:01 UTC, reinhello approved these changes

2022-09-27 12:02 UTC, merged

2022-09-28 05:03 UTC, darccyy commented
Thanks!